name: hello_webview
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  permission_handler: ^11.3.1  
  url_launcher: ^6.1.10 #extra code started here
  file_picker: ^5.3.2
  flutter_web_browser: ^0.17.1
  whatsapp_unilink: ^2.1.0
  #font_awesome_flutter: ^8.10.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  

flutter:
  uses-material-design: true
  #assets:
  #  - assets/whatsapp_icon.png
  #  - images/a_dot_burr.jpeg 
    
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
